In [20]:
import sys
!{sys.executable} -m pip install pandas
!{sys.executable} -m pip install sklearn
!{sys.executable} -m pip install tensorflow

     |████████████████████████████████| 454.4 MB 11 kB/s  eta 0:00:01    |███▊                            | 53.3 MB 1.1 MB/s eta 0:06:04     |█████▎                          | 75.1 MB 95 kB/s eta 1:05:52     |██████████████████▊             | 266.2 MB 92 kB/s eta 0:33:59     |██████████████████████          | 312.4 MB 36 kB/s eta 1:04:57     |███████████████████████         | 325.3 MB 359 kB/s eta 0:06:00     |█████████████████████████▋      | 364.2 MB 90 kB/s eta 0:16:39     |███████████████████████████▎    | 387.9 MB 585 kB/s eta 0:01:54
     |████████████████████████████████| 4.4 MB 166 kB/s eta 0:00:01
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
     |████████████████████████████████| 57 kB 244 kB/s eta 0:00:01
     |████████████████████████████████| 129 kB 117 kB/s eta 0:00:01
     |████████████████████████████████| 6.0 MB 210 kB/s eta 0:00:01
     |████████████████████████████████| 1.2 MB 339 kB/s eta 0:00:01
     |████████████████████████████████| 65 kB 244 kB/s eta

In [21]:
# Mengimpor library yang diperlukan
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [23]:
dataset = pd.read_csv("Data_bank_churn.csv")
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [24]:
x = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values
x, y

(array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
        [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
        [502, 'France', 'Female', ..., 1, 0, 113931.57],
        ...,
        [709, 'France', 'Female', ..., 0, 1, 42085.58],
        [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
        [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object),
 array([1, 0, 1, ..., 1, 1, 0]))

In [25]:
#Mengonversi data kategori Gender menjadi numerik
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
labelEncoder = LabelEncoder()
x[:, 2] = labelEncoder.fit_transform(x[:, 2])
x.shape

(10000, 10)

In [26]:
#Membuat dummy variable untuk Geography
columnTransformer = ColumnTransformer([("encoder", OneHotEncoder(), [1])], remainder="passthrough")
x = np.array(columnTransformer.fit_transform(x), dtype = np.int)
x.shape

(10000, 12)

In [27]:
#Menghilangkan 1 dummy variable
x = x[:, 1:]
x

array([[     0,      0,    619, ...,      1,      1, 101348],
       [     0,      1,    608, ...,      0,      1, 112542],
       [     0,      0,    502, ...,      1,      0, 113931],
       ...,
       [     0,      0,    709, ...,      0,      1,  42085],
       [     1,      0,    772, ...,      1,      0,  92888],
       [     0,      0,    792, ...,      1,      0,  38190]])

In [28]:
#Membagi training set dan test set
from sklearn.model_selection import train_test_split
xTrain, xTest, yTrain, yTest = train_test_split(x, y, test_size=0.2, random_state=0)
xTrain.shape

(8000, 11)

In [29]:
#Feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
xTrain = sc.fit_transform(xTrain)
xTest = sc.transform(xTest)

In [41]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

In [43]:
#Inisialisasi ANN
classifier = Sequential()
#Menambah input dan hidden layer pertama
classifier.add(Dense(units=11, kernel_initializer="uniform", activation="relu", input_dim=11))
#Menambah hidden layer kedua
classifier.add(Dense(units=11, kernel_initializer="uniform", activation="relu"))
classifier.add(Dense(units=11, kernel_initializer="uniform", activation="relu"))
#Menambah output layer
classifier.add(Dense(units=1, kernel_initializer="uniform", activation="sigmoid"))
#Menjalankan ANN
classifier.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])
#Fitting ANN ke training set
classifier.fit(xTrain, yTrain, batch_size=20, epochs=100)

Epoch 1/100
400/400 [==============================] - 1s 681us/step - loss: 0.5030 - accuracy: 0.7949
Epoch 2/100
400/400 [==============================] - 0s 723us/step - loss: 0.4264 - accuracy: 0.7971
Epoch 3/100
400/400 [==============================] - 0s 730us/step - loss: 0.4165 - accuracy: 0.8259
Epoch 4/100
400/400 [==============================] - 0s 718us/step - loss: 0.4090 - accuracy: 0.8317
Epoch 5/100
400/400 [==============================] - 0s 710us/step - loss: 0.4046 - accuracy: 0.8336
Epoch 6/100
400/400 [==============================] - 0s 680us/step - loss: 0.4026 - accuracy: 0.8338
Epoch 7/100
400/400 [==============================] - 0s 755us/step - loss: 0.4010 - accuracy: 0.8335
Epoch 8/100
400/400 [==============================] - 0s 777us/step - loss: 0.3996 - accuracy: 0.8351
Epoch 9/100
400/400 [==============================] - 0s 717us/step - loss: 0.3984 - accuracy: 0.8355
Epoch 10/100
400/400 [==============================] - 0s 776us/step - l

400/400 [==============================] - 0s 877us/step - loss: 0.3327 - accuracy: 0.8631
Epoch 80/100
400/400 [==============================] - 0s 864us/step - loss: 0.3306 - accuracy: 0.8641
Epoch 81/100
400/400 [==============================] - 0s 782us/step - loss: 0.3313 - accuracy: 0.8655
Epoch 82/100
400/400 [==============================] - 0s 801us/step - loss: 0.3321 - accuracy: 0.8620
Epoch 83/100
400/400 [==============================] - 0s 808us/step - loss: 0.3304 - accuracy: 0.8639
Epoch 84/100
400/400 [==============================] - 0s 820us/step - loss: 0.3304 - accuracy: 0.8620
Epoch 85/100
400/400 [==============================] - 0s 831us/step - loss: 0.3320 - accuracy: 0.8650
Epoch 86/100
400/400 [==============================] - 0s 830us/step - loss: 0.3321 - accuracy: 0.8650
Epoch 87/100
400/400 [==============================] - 0s 820us/step - loss: 0.3316 - accuracy: 0.8644
Epoch 88/100
400/400 [==============================] - 0s 816us/step - loss:

In [44]:
yPred = classifier.predict(xTest)
yPred

array([[0.30222523],
       [0.29065055],
       [0.14258954],
       ...,
       [0.184585  ],
       [0.16991588],
       [0.2458398 ]], dtype=float32)

In [59]:
yPred = (yPred > 0.5)
yPred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [61]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(yTest, yPred)
cm

array([[1491,  104],
       [ 177,  228]])